"""empty message

Revision ID: 36b2baab048e
Revises: 
Create Date: 2020-08-12 01:09:06.599949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b2baab048e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('User', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
