"""empty message

Revision ID: 715de3dadd1b
Revises: dae372741365
Create Date: 2020-08-12 14:51:33.916842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715de3dadd1b'
down_revision = 'dae372741365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Contest', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Contest', type_='unique')
    # ### end Alembic commands ###
